name: Ask Your Notes CI
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: setup git config
        run: |
          git config user.name veeda
          git config user.email veeda.dev@skiff.com
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - name: Install dependencies
        run: npm ci
      - name: Bump version
        run: |
          npm run release:patch
          git push --follow-tags origin ${{ github.head_ref }}
